language: node_js
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.5"
sudo: true
before_install:
  - sudo apt-get install -y postgresql-9.5-postgis-2.3
  - sudo service postgresql restart
  - psql -c 'create database bottleneck_development;' -U postgres
  - psql -U postgres -c "create extension postgis"
script: npm run-script coveralls
env:
  global:
    - DATABASE_URL=postgresql://postgres@localhost:5432/bottleneck_development
    - secure: "i/WRyAL8+WiL07QuasQOfi+8SIZ51VW7OFtIXsuWS8KSYoOdtsiBATf5Rh+KCAa1fE9LAbPdufMfn6ryP1LkL5QGRslXQMdYvLO0clodc3Ucgd7MKUUx9clVmkoQNVhb4OZjujJnVEKr2L7+M6dcjglLRN4tMqOSYsULD3fm9jC26qJlP6CVeLU0YQp+ub0hcaX3bZtyasIkefyxc1LE4g1bxGjYqoCzy8QMS+McUCG3WAVSyFhemCtdAX//xD++IzZs5MgkyolD8lgwpsMQMndiBjKCOo1SWEEc7tX4iLCt9CRUXX2AySFte8GAfUK5LtfzVUlu+FznOWCTIsOlPuFiuB3lz4cfx05XO0xNbMk5gkatQRoYSj6Dfd9H3PtewC7YAXZK2EnolZufobPIvMc46BjyzgmHVK9y82gx7g+ywmrTU3yP0FM5ER+Zj7k1JCs/MiHqHN9UVxqpg6DEDdQvRx4Y5NQruxSGqdre0kLYJWM2nKZ051YnFRGI1R3OObSZ8QllrxgE0KuRBhX1HkYl+8pSMmQyP3XyIv2y5o6YCWdnC4RIJPd0VaCoNxApOWlBR+oLklZiU2SDJGWNDTR04leB8fp27rJpbyoKjzaNZmVZGFuEZ17JBVPsWA6i5W4GXCVuh2ghNZemQ0LBkY9VqG1WzwjjTVvImDl5XOY="
    - secure: "FUvCq8b2n1z24FsLV6L4lu7p9JhW0z3dTfN5OjaecMOgM87OY/3w48wEjQREFmaT0seW/VOySYLxD5GlXhVGSJkRgGue4g/tUiR6cwtgRF/zafsS/c6YUoxGwqVIKjpACFAxXf3lFlTHIpH4MB9VB2Xb3B8lXeOdFVi++a8Hiol5FA+EXPOxgPYvZjAI34H/2ltGS7fApcO36Txk4shiyLo0QN+2Uul+jzSuDfjtqktReFde5YJh3e/XobVJ0fvd57X5L3CJbeVs+3Uv15g1g+s3husq9Xd2QJ055JP9QawXr+4IWSgu3YpjZ31zt5ihXZL3lXQrbMWcHlcac+7PhbD/cYX5sXgpKHBOb/btrg6Znao4TetdBDOXT9ctUQ8EkDdEXPcz533PaM9WImtZlSH6Qtiva0lIrjrObh4QUZzKIl6G+nMep9cxtRzAJnb9Eoi3SiUUKXjjTrqz3JdhGRqkAN9LHttHkGA+JA/sc1OpOh5YpJgzoG/tGXkcWWNNVLMMW+B24f9TGsmYRur+3htai2PS6acpN5auYk3Tsiv562HM67fKe6kNPuv1MtwwY/4lYLM1aFag4XdwMZXiEP1V+EgELcoro8o/i8t5dj2VSVZh+LuHIa6+CcnYdM3+IoN5vJUbQqEb2DtwbhAJPBQdvGmXE3BHk/dRxM6dj/w="
    - secure: "gJTZWx1CSuQVMGeIyevsl3blxRnI6O2fwCZ6PgxelMooltUvok5q6s1w4QPxMHIUdCa92raHNeFP
  lt7SdMOM1xvGLkm606HBb9DDhr/I8gYIfXUk5Z0NjjUJs74i9pmAjg3bjJBrfZ6jXHzcxmUrcMIX
  NlwG6wlrUoyaHJ5ygl8GsCNgK+Z6awdi9Pp42a6Y/X5SK9m3zFtVXrOJrbIH6Ou6/OqXmo9Lx628
  dm1TFa75uL1GcyU984Y/4gYt2fg4SQpCgJkZNwX4sbz67r2geVvxblzLVHQEv01zcHvqn4SpPCKq
  dUL5JZb0hke21JKPlNjRR5SwURwJoj2akc6O+lOqxiQ179ONAPTPopo57yaesnV1AvyLLk6/31RE
  MtANsxZEE61roMyLmY/WIWVG4yaCl+jids89R1DwQL3wnrb/2u9lvX+ZVvlcJ2EWknUq3I5LFpaE
  zzL7ZnE5IhVHCESR5V4mOQVg+JKtc0NwHjA0MIgwg31AmFLy1QnoakDvMiMTrpShiyX2np0Mc7w9
  zds5Maj9pXxG4TrIlVBoclPeVc3iLYRGmqq6fXeqVQKP3C9uZglXPTQyIJP8ezvAsp3nMTNwramL
  I7v4bAFvs1kZxgpqiF+x7EsjkYfxHoO9pAXiQSmTwMgWasbHKMCDG4eM+cIkDGT0WHhHp6B6AVAO
  uZGzudwPcPjJgMsTXiv69iJd48J9niePfyqpw0419ujX12OIzg+4DTUDUy1G/+SvqeRClkJX65HH
  v5A/bGnxFuPx8inGUXSC2zIL6awJr4ki7SeUcd44ZfY9QtolyCqkgY5qYS1pkfaFUvAhblmtYYmv
  yy6aXChxSNJw0IqRx6wmU8+56MIbbIg/gLYbAhIEtelXKUXbieUubcRJHuLRM02C1T5Aix4CdxOR
  MPO6crRf60gZfJ5Z3HJ58Kq8PkJ0/2JQ5Jc49sRQipR+8w0OHflA8Ore5O7dTq93N6fClrup4OYx
  KGFTU6YZfsIJ+Fylj8lXb4HRZQg8jUAoMsTSCJ7WAOAWfW/iWPef6CC3GzFkuyXoXmoVtSxyih+0
  bZePxqrt4fl4dfBTxz2pLCeSpMgM/KWeH5UUh2ilymSVPa2aUYlmb7btlZXtiv33mxzmNLx4bJJr
  ieDfmb5vaDN+BSYnR9mLy2RJ7RAigp6MGjuUdKbvZb9eviNN71x2Q6qld/Fh+M391pPAsZRi1Pcs
  grZ//NVItCKIaF025M3cnJXJc8SlTBRkCbeg7OMCsgT9ZJ/xGorkhFuENLAXx/5+dFqlLjmC68MS
  vpgJeFxIadvQB7vV1LpUDw1fIEu/caMx+4tgfl8SF3FDmuz3OaymO4nZ3T5MnL3HctjjMauuHTWH
  L9wT96VxCMhEVHK5EFp3dLsbyn79eXTvCeuEPpNe4mgwkY9yISbABulb0UzAovFPkInOAKw0UJfm
  ZjSz4nM9mF8y+cXtAhGY/RLo6GxhtlfKWtsL0X2kEZegm54As4no+Z+squrUa6hhSf7HylE2UgKL
  aJwxkQEpDUupJ4H3xfFlxVee63+ykyehUfW2Bfm7/BZ9Uw45viAWil/wSOPdU9dnRTeiUDbuNpOu
  eYIh54NnCBbl6I2/dEti+sFjFjAwllMTUX5FN/sbQTL6Mu0MZnuNx1nxG6X2OR+OA1HXqTKtYXKp
  MeFF+b6FYfOAouFleWiuFfs972fF+NseWExXLsS5ROJfewl8yU30+6vpwSkNkX4fzsqBzS3RhKy6
  3BAS8ZR1KPNrhHVIISkeavZoRm1LFTanmmid3MymXLcoCEF4v79u6KvFh5jsCK2ID/bgMoAXuylK
  Ji0/5qlCqQJBN2uwKBhPMHfPmzBfWdTYBlquO+L3lrD63PRF3fF73u0nEjR9sTJmN4OHolb/sdDN
  zc+GAKQ8ErCew75FTKS1gB5My5j4gqSkr69qPZu+yluNqZpczUkDxDtZ5M1Ni8Zyc/AlB8zSeHsP
  8o4fAZwk/+au/+0cHWeWee3E416omC1CA7QjjURslYWJkVtYjb2JrH4AmHH53gv5cc7DAbV5cuJg
  H9snSeQkcWBHdiCk/wfMZ1pBzxOBW2po80cB5iglsKari1mYOwBP/VGsbmamGgcRzbNZ0ruiqGtF
  mNoRyFwmCq4DmyaHvAwgYkW2dOalBGzK9oEZLgp0RmyKCzkn3j507we4mYdGrop5y+3CA1pFh/kY
  Od+KdLTU5cV1YnNrHtFppj5QBoUBljGvCaafK0gQUys0PG1R+Uod6Fud2H/tFCehpe9tBGr3razx
  3T1OZg2WFr27VAftJqwGn1vRVvAkgJyujsZntVOEXQiK+/d2P8fDV5STHOXeiDXTjsw="
